#application.yml

spring:
  application:
    name: InvoiceManager
  profiles:
    active: db, ai
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini

server:
  port: 8001
  address : 0.0.0.0
#  should be changed to fronted domain

logging:
  level:
    org:
      hibernate:
        type: trace