name: Java CI/CD
on:
  pull_request:
    types: [closed]
    branches: [develop]
jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    # 1. Checkout the code
    - uses: actions/checkout@v3

    # 2. Set up JDK (Java 17 for example)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    # 3. Build the Java project
    - name: Build the project
      run: ./gradlew build

    # 4. Copy the built JAR file to EC2
    - name: Copy JAR to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Setting up SSH key"
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        echo "Copying JAR file to EC2"
        scp -i private_key -o StrictHostKeyChecking=no build/libs/*.jar ${USER}@${HOST}:~/app/
        echo "Executing commands on EC2"
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd ~/app
          echo "JAR file copied successfully"
          ls -la
        '
