name: Java CI/CD
# test2
on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    env:
      HOST: ${{ secrets.EC2_HOST }}
      USER: ${{ secrets.EC2_USER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude='.git' --delete -e "ssh -i ~/.ssh/id_rsa" ./ $USER@$HOST:~/app/

    - name: Execute commands on EC2
      run: |
        ssh -i ~/.ssh/id_rsa $USER@$HOST '
          cd ~/app
          echo "Source code copied successfully"
          ls -la
          # Add any additional commands you want to run on the EC2 instance
        '

    - name: Clean up
      if: always()
      run: rm -rf ~/.ssh
