name: Java CI/CD
on:
  pull_request:
    types: [closed]
    branches: [develop]
jobs:
  copy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy source to Ec2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Setting up SSH key"
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        echo "Copying source code to EC2"
        scp -r -i private_key -o StrictHostKeyChecking=no * ${USER}@${HOST}:~/app/
        scp -r -i private_key -o StrictHostKeyChecking=no .* ${USER}@${HOST}:~/app/
        echo "Executing commands on EC2"
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd ~/app
          echo "Source code copied successfully"
          ls -la
        '
