name: Java CI/CD
on:
  pull_request:
    types: [closed]
    branches: [develop]
jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --info
    - name: List build artifacts
      run: ls -R build/libs
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "Setting up SSH key"
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        echo "Copying JAR file to EC2"
        scp -v -i private_key -o StrictHostKeyChecking=no build/libs/*.jar ${USER}@${HOST}:~/app/
        echo "Executing commands on EC2"
        ssh -v -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd ~/app
          echo "Stopping service"
          sudo systemctl stop invoice-manager
          echo "Moving JAR file"
          sudo mv *.jar invoice-manager.jar
          echo "Starting service"
          sudo systemctl start invoice-manager
          echo "Checking service status"
          sudo systemctl status invoice-manager
        '
